api:
  image: stackstorm/st2api
  links:
    - mongo
    - rabbitmq
  volumes_from:
    - data
  ports:
    - '9101:9101'

auth:
  image: stackstorm/st2auth
  links:
    - api
    - mongo
  volumes:
    - './auth/htpasswd:/etc/st2/htpasswd:ro'
  volumes_from:
    - data
  ports:
    - '9100:9100'

notifier:
  image: stackstorm/st2notifier
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

resultstracker:
  image: stackstorm/st2resultstracker
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

rulesengine:
  image: stackstorm/st2rulesengine
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

sensorcontainer:
  image: stackstorm/st2sensorcontainer
  links:
    - api
    - mongo
    - rabbitmq
  volumes_from:
    - data

actionrunner:
  build: ./actionrunner #[inline]
  links:
    - api
    - mongo
    - rabbitmq
    - web
  volumes_from:
    - data
  environment:
    ST2_ACTION_API_URL: https://web/api
    ST2_ACTION_AUTH_URL: https://web/auth

web:
  build: ./web
  links:
    - api
    - auth
  ports:
    - 80:80
    - 443:443

client:
  build: ./client
  links:
    - api
    - auth

chatops:
  build: ./chatops
  links:
    - web
  environment:
    ST2_HOSTNAME: web
    ST2_AUTH_USERNAME: admin
    ST2_AUTH_PASSWORD: 123
    HUBOT_ADAPTER: slack
    HUBOT_SLACK_TOKEN: xoxb-change-me

## External Services
mongo:
  image: mongo
  ports:
    - '27017:27017'

rabbitmq:
  image: rabbitmq

## Data container
data:
  build: ./data
  volumes:
    - /etc/st2
    - /opt/stackstorm
  links:
    - rabbitmq
    - mongo
